version: '2'

services:
  spring-boot-app:
    build: .
    ports:
      - "1111:8080"
    environment:
      - POSTGRES_URL=jdbc:postgresql://217.25.92.9:5433/berrielocal
      - POSTGRES_LOGIN=gen_user
      - POSTGRES_PASSWORD=BCAlhlM?A27@pl
