version: '2'

services:
  psql-db:
    image: postgres
    container_name: psql-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: berrielocal
    expose:
      - 5433
    ports:
      - "5433:5432"
    networks:
      - app-network

  spring-boot-app:
    build: .
    ports:
      - "1111:8080"
    depends_on:
      - psql-db
    environment:
      - POSTGRES_URL=jdbc:postgresql://217.25.92.9:5433/berrielocal
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
