version: '2'

services:
  spring-boot-app:
    build: .
    ports:
      - "1111:8080"
    environment:
      - POSTGRES_URL=jdbc:postgresql://147.45.107.100/berrielocal
      - POSTGRES_LOGIN=gen_user
      - POSTGRES_PASSWORD=BCAlhlM?A27@pl
