spring:
  datasource:
    url: ${POSTGRES_URL}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_LOGIN}
    password: ${POSTGRES_PASSWORD}
  flyway:
    enabled: true
    locations: classpath:db
  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: berrielocal@gmail.com
    password: ivst vvpj iojh otpx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret:
    access: 0LzQsNGA0LzQt44123bffgadsfag70LDQtA==
    refresh: 0L/QvtC90Yfasdasdasbnbkjqwweq5688975QuNC60Lg=
  expiration:
    access: 36000000
    refresh: 8640000000
